### ISSUE TITLE
Documentation on new_version_code is misleading

### ISSUE THREAD

**Issue by fabiendem** [bitrise-steplib/steps-change-android-versioncode-and-versionname#27]
Hey,

Looking at the `new_version_code` section of the step:
https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/blob/00d989bfc8a69a834b70222e4499d81cf9582556/step.yml#L76-L90

Documentation says "Leave this input empty to do not modify versionCode."
But `new_version_code` defaults to `$BITRISE_BUILD_NUMBER`
`new_version_code: $BITRISE_BUILD_NUMBER`

Reading the doc, it could be interpreted so that if `new_version_code` is not mentionned:
```
      - change-android-versioncode-and-versionname@1.2.3:
          inputs:
            - build_gradle_path: "$ANDROID_PROJECT_PATH/$ANDROID_MODULE/build.gradle"
            - new_version_name: "New Version name"
```
the step would "not modify versionCode".

But instead it will default to `$BITRISE_BUILD_NUMBER` and actually modify the `versionCode`.

We have a similar setup and it took me a while to understand how on earth the `new_version_code` was getting bumped 😅 

What do you think about not defaulting to `$BITRISE_BUILD_NUMBER` in the step (breaking change) or maybe tweaking the doc for clarity?

Cheers!
